# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.4.0

COPY ./Kibana.yml /usr/share/kibana/config/
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
