# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.4.1
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
RUN rm -f /usr/share/logstash/config/logstash.yml

COPY ./logstash.conf /usr/share/logstash/pipeline
COPY ./logstash.yml /usr/share/logstash/config/



# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
